services:

  fogbus2-diabetes_voter2:
    image: cloudslab/fogbus2-diabetes_voter2:1.0
    build:
      context: ../../
      dockerfile: dockerFiles/DiabetesVoter2/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
