services:

  fogbus2-roadside_camera_object_detection:
    image: cloudslab/fogbus2-roadside_camera_object_detection10:1.0
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    ports:
      - 10000:10000